### ISSUE TITLE
Comparing to PHP Refactor Browser

### ISSUE THREAD

**Issue by mtangoo** [phparty/refactor-php#10]
Hi,
I know your work is still infant and wanted to know if I should keep my eye on it.

How does it compare and contrast to https://github.com/QafooLabs/php-refactoring-browser

**Comment by falnyr** [comment]
Hey there,
the package you mention is of a different nature.

Our tool is not meant to be a replacement for IDE available refactoring like "Extract fragment of code to a method", but completely customisable refactoring rules. E.g. In case you call function "foo" with first argument "bar", replace the node with new class call.

Transforming this:
`$result = foo('bar', 'baz');`

Into this:
`$result = new FooBar('baz');`

These kind of operations with code are necessary mostly when dealing with tons of legacy code that needs to be refactored. This is where what we aim for.

**Comment by mtangoo** [comment]
Ok thanks. I hope to see documentation on how it works
